[project]
name = "models"
version = "0.1.0"
description = "Implement various Deep Learning models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.0.0",
    "einops>=0.8.1",
    "hf-xet>=1.1.7",
    "litestar>=2.17.0",
    "litestar-granian>=0.14.2",
    "litestar-vite>=0.13.2",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "opencv-python>=4.11.0.86",
    "pandas>=2.3.1",
    "polars>=1.32.2",
    "pydantic>=2.11.7",
    "pydantic-tensor>=0.2.0",
    "safetensors>=0.6.1",
    "scipy>=1.16.1",
    "seaborn>=0.13.2",
    "tinygrad>=0.10.3",
    "torch>=2.8.0",
    "torchinfo>=1.8.0",
    "torchvision>=0.23.0",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
    "jupyter>=1.1.1",
    "lefthook>=1.12.2",
    "poethepoet>=0.36.0",
    "ruff>=0.12.7",
]

[tool.uv]

[tool.poe.tasks]
app = "uv run litestar --app app:app run"
main = "main.py"
format = "ruff format ."
lint = "ruff check --fix ."


[[tool.uv.index]]
name = "pytorch-cu129"
url = "https://download.pytorch.org/whl/cu129"
explicit = true


[tool.uv.sources]
torch = [{ index = "pytorch-cu129" }]
torchvision = [{ index = "pytorch-cu129" }]

[tool.basedpyright]
include = ["src"]
reportUnknownMemberType = false
reportUnknownVariableType = false
reportAny = false
reportExplicitAny = false
reportUnknownArgumentType = false
reportUnknownParameterType = false
reportUnknownLambdaType = false
