from typing import Literal


dataset_names = Literal[
    "mnist", "cifar10", "cifar100", "fashion_mnist", "imagenet", "mini_imagenet"
]
model_names = Literal[
    "example_cnn",
    "le_net",
    "alex_net",
    "vgg_net11",
    "vgg_net13",
    "vgg_net16",
    "vgg_net19",
    "res_net18",
    "res_net34",
    "res_net50",
    "res_net101",
    "res_net152",
    "inception_v1",
    "inception_v2",
    "dense_net_cifar",
    "dense_net121",
    "dense_net169",
    "dense_net201",
    "dense_net264",
    "mobile_net",
    "shuffle_net_v1",
    "efficient_net_v1_b0",
    "efficient_net_v1_b1",
    "efficient_net_v1_b2",
    "efficient_net_v1_b3",
    "efficient_net_v1_b4",
    "efficient_net_v1_b5",
    "efficient_net_v1_b6",
    "efficient_net_v1_b7",
    "efficient_net_v1_b8",
    "efficient_net_v1_l2",
    "gan",
]
loss_function_names = Literal[
    "l1",
    "nll",
    "poisson_nll",
    "gaussian_nll",
    "kl_div",
    "mse",
    "bce",
    "bce_with_logits",
    "hinge_embedding",
    "multi_label_margin",
    "smooth_l1",
    "huber",
    "soft_margin",
    "cross_entropy",
    "multi_label_soft_margin",
    "cosine_embedding",
    "margin_ranking",
    "multi_margin",
    "triplet_margin",
    "triplet_margin_with_distance",
    "ctc",
]
optimizer_names = Literal[
    "adafactor",
    "adadelta",
    "adagrad",
    "adam",
    "adamax",
    "adamw",
    "asgd",
    "lbfgs",
    "nadam",
    "radam",
    "rmsprop",
    "rprop",
    "sgd",
    "sparse_adam",
]
